Traceback (most recent call last):
  File "face_check.py", line 82, in <module>
    show_face()
  File "face_check.py", line 57, in show_face
    sys.stdout.write("-----------"+user_id)
NameError: global name 'sys' is not defined
